# Generated by Django 5.2 on 2026-08-14 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rover',
            fields=[
                ('id_rover', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('bateria', models.FloatField(default=100.0)),
                ('ultima_conexao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telemetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umidade_solo', models.FloatField(blank=True, null=True)),
                ('umidade_ar', models.FloatField(blank=True, null=True)),
                ('temperatura_ar', models.FloatField(blank=True, null=True)),
                ('qualidade_ar', models.FloatField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('sinal_lora_rssi', models.IntegerField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('rover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rover.rover')),
            ],
        ),
    ]
